apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: source-postgres
  namespace: database
spec:
  teamId: poc
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    source-user: [replication, login]
  databases:
    source_db: source-user
  postgresql:
    version: "15"
    parameters:
      wal_level: logical
