apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: sink-jdbc-connector
  namespace: messaging
  labels:
    strimzi.io/cluster: sink-connect
spec:
  class: io.debezium.connector.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: source.source.public.weather_readings
    connection.url: jdbc:postgresql://sink-postgres.database.svc.cluster.local:5432/sink_db
    connection.username: sink-user
    connection.password: SINK_DB_PASSWORD
    table.name.format: public.weather_readings
    schema.evolution: basic
    schema.evolution.drop: "false"
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: drop
    insert.mode: upsert
    primary.key.mode: record_value
    primary.key.fields: id
