apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: sink-connect
  namespace: messaging
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: local/kafka-connect:3.4.1
  replicas: 1
  bootstrapServers: sink-kafka-kafka-bootstrap:9092
  groupId: sink-connect
  configStorageTopic: sink-connect-configs
  offsetStorageTopic: sink-connect-offsets
  statusStorageTopic: sink-connect-status
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
