apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: sink-dual-role
  namespace: messaging
  labels:
    strimzi.io/cluster: sink-kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
