apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: weather-readings
  namespace: messaging
  labels:
    strimzi.io/cluster: source-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact
